---
  title: "Centre of Gravity"
  output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath('../'))
```

```{r load, include=FALSE, message=FALSE}
# load packages etc.
source("scripts/header.R")
load("input/spatial_model_data.rData")
```

```{r functions, include=FALSE}
# plot result
plot.report <- function(df) {

  #if (nrow(df$data[[1]]) < 3) return(NULL)

  layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE), heights = c(1.5,1))

  plot(df$statrec[[1]], main = paste0(df$species, " ", df$Survey, " Q", df$Quarter), border = grey(0.5, alpha=0.5))
  #plot(area, border = grey(0.7, alpha=0.5), add = TRUE)
  pdat <- df %>% unnest(data) %>% unnest(cg, cg_ci)
  lines(pdat$y, pdat$x)
  years <- pdat$Year - min(pdat$Year) + 1
  nyears <- max(years)
  cols <- colorRampPalette(c("cyan", "magenta"))(nyears)
  points(pdat$y, pdat$x, col = cols[years], pch = 16)

  plot(pdat$Year, pdat$x, type = "l", ylim = range(pdat$x, pdat$x.ciu, pdat$x.cil),
       axes = FALSE, ylab = "Latitude", xlab = "Year")
  points(pdat$Year, pdat$x)
  lines(pdat$Year, pdat$x.cil, lty = 2)
  lines(pdat$Year, pdat$x.ciu, lty = 2)
  axis(1); axis(2, las = 1); box(bty="l")

  plot(pdat$Year, pdat$y, type = "l", ylim = range(pdat$y, pdat$y.ciu, pdat$y.cil),
       axes = FALSE, ylab = "Longitude", xlab = "Year")
  points(pdat$Year, pdat$y)
  lines(pdat$Year, pdat$y.cil, lty = 2)
  lines(pdat$Year, pdat$y.ciu, lty = 2)
  axis(1); axis(2, las = 1); box(bty="l")

}
```




