---
  title: "Distribution shifts - Tables"
  output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath('../'))
```

```{r load, include=FALSE, message=FALSE}
# load packages etc.
source("scripts/header.R")
load("input/spatial_model_data.rData")
```

# Tables
## Spurdog

```{r Spurdog, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Spurdog_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Spurdog',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Herring

```{r Herring, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Herring_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Herring',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Sprat

```{r Sprat, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Sprat_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Sprat',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Anchovy

```{r Anchovy, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Anchovy_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Anchovy',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Cod

```{r Cod, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Cod_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Cod',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Haddock

```{r Haddock, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Haddock_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Haddock',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Whiting

```{r Whiting, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Whiting_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Whiting',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Blue Whiting

```{r Blue Whiting, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Blue Whiting_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Blue Whiting',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Pollack

```{r Pollack, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Pollack_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Pollack',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Saithe

```{r Saithe, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Saithe_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Saithe',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Hake

```{r Hake, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Hake_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Hake',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Horse Mackerel

```{r Horse Mackerel, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Horse Mackerel_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Horse Mackerel',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Mackerel

```{r Mackerel, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Mackerel_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Mackerel',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Megrim

```{r Megrim, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Megrim_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Megrim',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Plaice

```{r Plaice, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Plaice_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Plaice',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


## Sole

```{r Sole, dpi=300, fig.width=8, fig.height=7, echo=FALSE, message=FALSE}
load('output/Sole_trends.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)

# plot log ratios
tmp <- unnest(stocks, data)
tmp <- left_join(res, tmp)
if (nrow(res)>0) {
p <- xyplot(val ~ Year | paste0(Division1, ' ~ ', Division2, ' (', round(slope,2), ')'), groups = id,
       data = subset(tmp, id %in% 1:100),
       type = c('p', 'r'), col = grey(0.5, alpha = 0.3), pch = 16,
       scale = list(y = list(relation = 'free')),
      main = 'Sole',
      layout = c(4, 2), as.table = TRUE)
print(p)
}
```


