---
  title: "Distribution shifts"
  output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath('../'))
```

```{r load, include=FALSE, message=FALSE}
# load packages etc.
source("scripts/header.R")
load("input/spatial_model_data.rData")
```

```{r functions, include=FALSE}
# plot result
plot_result <- function(res, area, main = "") {

  xy <- coordinates(area)

  # get coords of arrows and lines
  x0 = xy[ifelse(res$slope < 0, res$TAC1, res$TAC2),1]
  y0 = xy[ifelse(res$slope < 0, res$TAC1, res$TAC2),2]
  x1 = xy[ifelse(res$slope < 0, res$TAC2, res$TAC1),1]
  y1 = xy[ifelse(res$slope < 0, res$TAC2, res$TAC1),2]

  plot(area, border = grey(0.5, alpha = 0.5), main = main)
  segments(x0, y0, x1, y1,
           col = "blue", lwd = 1)

  # shorten arrow
  arrows(x0, y0, x0+(x1-x0)*.45, y0 + (y1-y0)*.45,
         col = "blue", lwd = 2,
         code = 2, length = 0.1)
  points(xy, pch = 16, col = "red", cex = 0.8)
}
```




