---
  title: "Distribution shifts"
  output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath('../'))
```

```{r load, include=FALSE, message=FALSE}
# load packages etc.
source("scripts/header.R")
load("input/spatial_model_data.rData")
```

```{r functions, include=FALSE}
# plot result
plot_result <- function(res, area, main = "") {

  xy <- coordinates(area)

  # get coords of arrows and lines
  x0 = xy[ifelse(res$slope < 0, res$TAC1, res$TAC2),1]
  y0 = xy[ifelse(res$slope < 0, res$TAC1, res$TAC2),2]
  x1 = xy[ifelse(res$slope < 0, res$TAC2, res$TAC1),1]
  y1 = xy[ifelse(res$slope < 0, res$TAC2, res$TAC1),2]

  plot(area, border = grey(0.5, alpha = 0.5), main = main)
  segments(x0, y0, x1, y1,
           col = "blue", lwd = 1)

  # shorten arrow
  arrows(x0, y0, x0+(x1-x0)*.45, y0 + (y1-y0)*.45,
         col = "blue", lwd = 2,
         code = 2, length = 0.1)
  points(xy, pch = 16, col = "red", cex = 0.8)
}
```




## Megrim

```{r Megrim_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Megrim_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Megrim')
}
```

## Plaice

```{r Plaice_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Plaice_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Plaice')
}
```

## Sole

```{r Sole_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Sole_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Sole')
}
```

## Anchovy

```{r Anchovy_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Anchovy_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Anchovy')
}
```

## Black-bellied anglerfish

```{r Black-bellied anglerfish_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Black-bellied anglerfish_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Black-bellied anglerfish')
}
```

## White anglerfish

```{r White anglerfish_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/White anglerfish_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'White anglerfish')
}
```

## Blue Whiting

```{r Blue Whiting_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Blue Whiting_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Blue Whiting')
}
```

## Cod

```{r Cod_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Cod_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Cod')
}
```

## Haddock

```{r Haddock_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Haddock_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Haddock')
}
```

## Hake

```{r Hake_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Hake_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Hake')
}
```

## Herring

```{r Herring_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Herring_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Herring')
}
```

## Horse Mackerel

```{r Horse Mackerel_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Horse Mackerel_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Horse Mackerel')
}
```

## Mackerel

```{r Mackerel_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Mackerel_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Mackerel')
}
```

## Norway Pout

```{r Norway Pout_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Norway Pout_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Norway Pout')
}
```

## Pollack

```{r Pollack_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Pollack_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Pollack')
}
```

## Saithe

```{r Saithe_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Saithe_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Saithe')
}
```

## Spurdog

```{r Spurdog_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Spurdog_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Spurdog')
}
```

## Sprat

```{r Sprat_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Sprat_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Sprat')
}
```

## Whiting

```{r Whiting_plot, dpi=600, fig.width=7, fig.height=7, echo=FALSE}
load('output/Whiting_trends_tac.rData')
res$p_adj <- p.adjust(res$median_p, method = 'BH')
res %<>% filter(p_adj < 0.05) %>% select(-p)
if (nrow(res)>0) {
plot_result(res, main = 'Whiting')
}
```

